### PR TITLE
Vale of Shadows exterior INI only uses two spawn points out of 16.

### PR DESCRIPTION
**Pull request by GraionDilach**

### CODE REVIEW

**Comment by GraionDilach** [comment]
The l prefix does make this one questionable, but the specifics are bumped appropriately. I think this one's a typo carried over from oIWD.

**Comment by GraionDilach** [comment]
What can also be questioned if ENTERSPAWN should also be enabled, because [spawn_main] also lacks the enter= definition.

**Comment by lynxlynxlynx** [comment]
There's both a lshadow1 and shadow1 definition, so part of this was almost undeniably intentional.

**Comment by GraionDilach** [comment]
Well, since we couldn't agree on this one, I'll try to find time to move it to UB_IWD.

**Pull request closed without merging**
