### PR TITLE
Opcode 39 overhaul

### PR DESCRIPTION
**Pull request by 4Luke4**
See [here](https://www.gibberlings3.net/forums/topic/35902-opcode-39-issues/) for further details.

Basically:
- Trolls are no longer immune to Sleep
  - I suspect they are immune to Sleep because they used to rely on scripts for their special revive mechanics.
    - However, since this is no longer the case, I do not see why they should be immune to it...
- Spells such as Chaotic Commands no longer protect against Earthquake and Nausea. In particular:
  - magically levitating creatures, flying creatures, oozes, incorporeal creatures are now immune to Earthquake-like attacks
  - the various creatures that are immune to `op39` are immune to both Sleep and Nausea attacks
    - This also implies that creatures such as Dragons get Nausea immunity, which in theory would be incorrect
      - However, as stated in the thread above, a more fine-grained solution would probably be too much for a fixpack...
- Spells that remove `op2` (Cure Sleep) now remove only true Sleep attacks
  - So for instance, Exaltation (`ohtyr1.spl`) cannot remove neither Earthquake nor Stinking Cloud. It can only remove Sleep, Emotion: Hopelessness, Color Spray and the like...
- As far as Knockback is concerned (see f.i. `spin695.spl` - Wing Buffet), creatures whose animation is hardcoded to be immune to [op235](https://gibberlings3.github.io/iesdp/opcodes/bgee.htm#op235) are now immune to the short-duration `op39` effect that accompanies `op235`
  - All other creatures are vulnerable to it (this is hopefully not a problem since this short-duration `op39` is only meant to temporary disable the targeted creatures during the buffet...)

This PR also provides the following fixes:
- **Earthquake**
  - Make sure all effects bypass Magic Resistance (since the spell is supposed to alter the environment instead of directly affecting the targeted creatures)
    - As of now, the damage opcode (`op12`) bypasses MR, whereas the Sleep opcode (`op39`) does not. I opted for `resist_dispel=0` for the aforementioned reason...
  - [iwdee] Creatures with 10 or more Hit Dice should be immune to this spell (as per spell description)
- [bgee] ****Stinking Cloud****
  - op324's `resource` field should not be empty
- [bgee] **bdsleep.spl**
  - Make sure all effects bypass Magic Resistance / are dispellable (so as to match `op39`, which bypasses MR and it's dispellable)

### CODE REVIEW

**Comment by 4Luke4** [comment]
@CamDawg 
I am going to restrict this to [EEex](https://github.com/Bubb13/EEex/pull/61) only for better compatibility with existing mods.

**Comment by Argent77** [comment]
Shouldn't the fixpack be an [EEex-free](https://www.gibberlings3.net/forums/topic/34894-discussion-opcodes-109-175-185-paralyze-and-hold/?do=findComment&comment=326176) zone?

**Comment by szaumoor** [comment]
I thought this project was made with the hope that it was at some point integrated in an official patch (if that ever comes). I remember reading that at the beginning of the project. An external dependency such as EEex is probably out of the scope, I would think...

Maybe a separate "addon" file would be more appropriate, or as a part of any sort of tweak mod.

**Comment by 4Luke4** [comment]
> Shouldn't the fixpack be an [EEex-free](https://www.gibberlings3.net/forums/topic/34894-discussion-opcodes-109-175-185-paralyze-and-hold/?do=findComment&comment=326176) zone?

Yes, you are right...
However, as far as this specific fix is concerned, if you do not use EEex, then you are forced to break mods (unless I'm missing something of course...).

That is to say, without EEex you should remove all `op101` targeting `op39` from spells/items and rely upon `op206`/`op318`... So if a mod still uses `op101` (`p2=op39`), then Earthquake, Stinking Cloud and the like will continue to be blocked...

**Comment by 4Luke4** [comment]
@Argent77 , @CamDawg 

Ok, I coded up an alternate solution that does not require `EEex`.
However, I am now abusing [op182](https://www.gibberlings3.net/forums/topic/35616-effect-immunities-on-the-ee-engine-aka-taking-full-advantage-of-the-ee-fixpack/?do=findComment&comment=313805) so as to make the least minimal changes (that is to say, so as not to break existing mods...)

**Comment by 4Luke4** [comment]
Closed in favor of #59.

**Pull request closed without merging**
